site_name: Освоение алгоритмов

nav:
  - Начало:
    - Привет!: section_1/index.md
    - Начнём: section_1/page_1.md
  - Массивы и хеш-структуры:
    - Введение: arrays/index.md
    - Two sum: arrays/two_sum.md
    - Contains Duplicate: arrays/contains_duplicate.md
    - Valid Anagram: arrays/valid_anagram.md
    - Group Anagrams: arrays/group_anagrams.md
    - Top K Frequent Elements: arrays/top_k_frequent_elements.md
    - Product of Array Except Self: arrays/product_of_array_except_self.md
    - Valid Sudoku: arrays/valid_sudoku.md
    - Largest Number: arrays/largest_number.md
    - Longest Consecutive Sequence: arrays/longest_consecutive_sequence.md
  - Стэк-куча:
    - Введение: stack_heap/index.md
    - Valid Parentheses: stack_heap/valid_parentheses.md
    - Min Stack: stack_heap/min_stack.md
    - Evaluate Reverse Polish Notation: stack_heap/evaluate_reverse_polish_notation.md
    - Generate Parentheses: stack_heap/generate_parentheses.md
    - Daily Temperatures: stack_heap/daily_temperatures.md
    - Car Fleet: stack_heap/car_fleet.md
    - Largest Rectangle in Histogram: stack_heap/largest_rectangle_in_histogram.md
  - Два указателя:
    - Введение: two_pointers/index.md
    - Valid Palindrome: two_pointers/valid_palindrome.md
    - Two Sum II: two_pointers/two_sum_ii.md
    - 3Sum: two_pointers/3sum.md
    - Container With Most Water: two_pointers/container_with_most_water.md
    - Trapping Rain Water: two_pointers/trapping_rain_water.md
  - Скользящее окно:
    - Введение: sliding_window/index.md
    - Best Time to Buy and Sell Stock: sliding_window/best_time_to_buy_and_sell_stock.md
    - Longest Substring Without Repeating Characters: sliding_window/longest_substring_without_repeating_characters.md
    - Longest Repeating Character Replacement: sliding_window/longest_repeating_character_replacement.md
    - Permutation in String: sliding_window/permutation_in_string.md
    - Minimum Window Substring: sliding_window/minimum_window_substring.md
    - Sliding Window Maximum: sliding_window/sliding_window_maximum.md
  - Связные списки:
    - Введение: linked_lists/index.md
    - Reverse Linked List: linked_lists/reverse_linked_list.md
    - Merge Two Sorted Lists: linked_lists/merge_two_sorted_lists.md
    - Reorder List: linked_lists/reorder_list.md
    - Remove Nth Node From End of List: linked_lists/remove_nth_node_from_end_of_list.md
    - Copy List with Random Pointer: linked_lists/copy_list_with_random_pointer.md
    - Add Two Numbers: linked_lists/add_two_numbers.md
    - Linked List Cycle: linked_lists/linked_list_cycle.md
    - Find the Duplicate Number: linked_lists/find_the_duplicate_number.md
    - LRU Cache: linked_lists/lru_cache.md
    - Merge K Sorted Lists: linked_lists/merge_k_sorted_lists.md
    - Reverse Nodes in k-Group: linked_lists/reverse_nodes_in_k_group.md
  - Деревья:
    - Введение: trees/index.md
    - Invert Binary Tree: trees/invert_binary_tree.md
    - Maximum Depth of Binary Tree: trees/maximum_depth_of_binary_tree.md
    - Diameter of Binary Tree: trees/diameter_of_binary_tree.md
    - Balanced Binary Tree: trees/balanced_binary_tree.md
    - Same Tree: trees/same_tree.md
    - Subtree of Another Tree: trees/subtree_of_another_tree.md
    - Lowest Common Ancestor of a Binary Search Tree: trees/lowest_common_ancestor_of_a_binary_search_tree.md
    - Binary Tree Level Order Traversal: trees/binary_tree_level_order_traversal.md
    - Binary Tree Right Side View: trees/binary_tree_right_side_view.md
    - Count Good Nodes in Binary Tree: trees/count_good_nodes_in_binary_tree.md
    - Kth Smallest Element in a BST: trees/kth_smallest_element_in_a_bst.md
    - Construct Binary Tree from Preorder and Inorder Traversal: trees/construct_binary_tree_from_preorder_and_inorder_traversal.md
    - Binary Tree Maximum Path Sum: trees/binary_tree_maximum_path_sum.md
    - Serialize and Deserialize Binary Tree: trees/serialize_and_deserialize_binary_tree.md
  - Префиксное дерево:
    - Введение: trie/index.md
    - Implement Trie (Prefix Tree): trie/implement_trie_prefix_tree.md
    - Design Add and Search Words Data Structure: trie/design_add_and_search_words_data_structure.md
    - Word Search II: trie/word_search_ii.md
  - Поиск с возвратом:
    - Введение: backtracking/index.md
    - Subsets: backtracking/subsets.md
    - Combination Sum: backtracking/combination_sum.md
    - Permutations: backtracking/permutations.md
    - Subsets II: backtracking/subsets_ii.md
    - Combination Sum II: backtracking/combination_sum_ii.md
    - Word Search: backtracking/word_search.md
    - Palindrome Partitioning: backtracking/palindrome_partitioning.md
    - Letter Combinations of a Phone Number: backtracking/letter_combinations_of_a_phone_number.md
    - N-Queens: backtracking/n_queens.md
  - Приоритетная очередь:
    - Введение: priority_queue/index.md
    - Kth Largest Element in a Stream: priority_queue/kth_largest_element_in_a_stream.md
    - Last Stone Weight: priority_queue/last_stone_weight.md
    - K Closest Points to Origin: priority_queue/k_closest_points_to_origin.md
    - Kth Largest Element in an Array: priority_queue/kth_largest_element_in_an_array.md
    - Task Scheduler: priority_queue/task_scheduler.md
    - Design Twitter: priority_queue/design_twitter.md
    - Find Median from Data Stream: priority_queue/find_median_from_data_stream.md
  - Жадные алгоритмы:
    - Введение: greedy/index.md
    - Maximum Subarray: greedy/maximum_subarray.md
    - Jump Game: greedy/jump_game.md
    - Jump Game II: greedy/jump_game_ii.md
    - Gas Station: greedy/gas_station.md
    - Hand of Straights: greedy/hand_of_straights.md
    - Merge Triplets to Form Target Triplet: greedy/merge_triplets_to_form_target_triplet.md
    - Partition Labels: greedy/partition_labels.md
    - Valid Parenthesis String: greedy/valid_parenthesis_string.md
  - Графы:
    - Введение: graphs/index.md
    - Number of Islands: graphs/number_of_islands.md
    - Clone Graph: graphs/clone_graph.md
    - Max Area of Island: graphs/max_area_of_island.md
    - Pacific Atlantic Water Flow: graphs/pacific_atlantic_water_flow.md
    - Surrounded Regions: graphs/surrounded_regions.md
    - Rotting Oranges: graphs/rotting_oranges.md
    - Minesweeper: graphs/minesweeper.md
    - Course Schedule: graphs/course_schedule.md
    - Course Schedule II: graphs/course_schedule_ii.md
    - Redundant Connection: graphs/redundant_connection.md
    - Number of Operations to Make Network Connected: graphs/number_of_operations_to_make_network_connected.md
    - Word Ladder: graphs/word_ladder.md
  - Продвинутые графы:
    - Введение: advanced_graphs/index.md
    - Reconstruct Itinerary: advanced_graphs/reconstruct_itinerary.md
    - Min Cost to Connect All Points: advanced_graphs/min_cost_to_connect_all_points.md
    - Network Delay Time: advanced_graphs/network_delay_time.md
    - Swim in Rising Water: advanced_graphs/swim_in_rising_water.md
    - Longest Increasing Path in a Matrix: advanced_graphs/longest_increasing_path_in_a_matrix.md
    - Cheapest Flights Within K Stops: advanced_graphs/cheapest_flights_within_k_stops.md
  - Одномерное ДП:
    - Введение: dp_1d/index.md
    - Climbing Stairs: dp_1d/climbing_stairs.md
    - Min Cost Climbing Stairs: dp_1d/min_cost_climbing_stairs.md
    - House Robber: dp_1d/house_robber.md
    - House Robber II: dp_1d/house_robber_ii.md
    - Longest Palindromic Substring: dp_1d/longest_palindromic_substring.md
    - Palindromic Substrings: dp_1d/palindromic_substrings.md
    - Decode Ways: dp_1d/decode_ways.md
    - Coin Change: dp_1d/coin_change.md
    - Maximum Product Subarray: dp_1d/maximum_product_subarray.md
    - Word Break: dp_1d/word_break.md
    - Longest Increasing Subsequence: dp_1d/longest_increasing_subsequence.md
    - Partition Equal Subset Sum: dp_1d/partition_equal_subset_sum.md
  - Двумерное ДП:
    - Введение: dp_2d/index.md
    - Unique Paths: dp_2d/unique_paths.md
    - Longest Common Subsequence: dp_2d/longest_common_subsequence.md
    - Best Time to Buy and Sell Stock with Cooldown: dp_2d/best_time_to_buy_and_sell_stock_with_cooldown.md
    - Coin Change 2: dp_2d/coin_change_2.md
    - Target Sum: dp_2d/target_sum.md
    - Interleaving String: dp_2d/interleaving_string.md
    - Longest Increasing Path in a Matrix: dp_2d/longest_increasing_path_in_a_matrix.md
    - Distinct Subsequences: dp_2d/distinct_subsequences.md
    - Edit Distance: dp_2d/edit_distance.md
    - Burst Balloons: dp_2d/burst_balloons.md
    - Regular Expression Matching: dp_2d/regular_expression_matching.md
  - Битовые операции:
    - Введение: bit_manipulation/index.md
    - Single Number: bit_manipulation/single_number.md
    - Number of 1 Bits: bit_manipulation/number_of_1_bits.md
    - Counting Bits: bit_manipulation/counting_bits.md
    - Reverse Bits: bit_manipulation/reverse_bits.md
    - Missing Number: bit_manipulation/missing_number.md
    - Sum of Two Integers: bit_manipulation/sum_of_two_integers.md
    - Reverse Integer: bit_manipulation/reverse_integer.md
  - Математика и геометрия:
    - Введение: math_geometry/index.md
    - Rotate Image: math_geometry/rotate_image.md
    - Spiral Matrix: math_geometry/spiral_matrix.md
    - Set Matrix Zeroes: math_geometry/set_matrix_zeroes.md
    - Happy Number: math_geometry/happy_number.md
    - Plus One: math_geometry/plus_one.md
    - Pow(x, n): math_geometry/powx_n.md
    - Multiply Strings: math_geometry/multiply_strings.md
    - Detect Squares: math_geometry/detect_squares.md


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Тёмная версия
      primary: custom
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Светлая версия
      primary: custom
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/a_cup_of_code
    - icon: fontawesome/brands/github
      link: https://github.com/by-Lazarev

extra_css:
  - 'assets/css/color_schema.css'

markdown_extensions:
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - admonition
    - attr_list
    - footnotes

copyright: |
  &copy; 2023 <a href="https://github.com/by-Lazarev" target="_blank" rel="noopener"> Lazarev Nikita</a>
